language: node_js

node_js:
  - '10'

install: yarn --frozen-lockfile

cache:
  yarn: true
  directories:
    - 'node_modules'
    - '.cache'

before_script:
  - yarn build

script:
  - yarn run test
