name: Upload to staging

on:
  issue_comment:
    type: created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const isValidPreview = (
              context.payload.issue.pull_request &&
              context.payload.comment.body === '/preview'
            );
            if (!isValidPreview) return;

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get PR Number
        id: vars
        run: echo "::set-output name=pr_number::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Gatsby Build
        run: npm run build-ci
        env:
          PATH_PREFIX: ${{ steps.vars.outputs.pr_number }}/

      - name: Upload to GCS
        run: gsutil -m rsync -R ./public/ gs://staging.nodejs.dev/${{ steps.vars.outputs.pr_number }}/

      - name: Comment on PR
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Please find a preview at: https://staging.nodejs.dev/${{ steps.vars.outputs.pr_number }}/'
            });
